### PR TITLE
Add optional_chain named field

### PR DESCRIPTION
**Pull request by stackmystack**
Optional chaining property/array access and optional function
calls now produce an `optional_chain` named field.

When traversing a parsed program, once can retrieve the operator by
looking at the source code, indeed, but it seems _hacky_ (in a bad
sense).

Checklist:
- [ ] All tests pass in CI.
- [x] The script/parse-examples passes without issues.
- [x] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by stackmystack** [comment]
Hello, is this the right place for these kinds of PRs?

**Comment by mjambon** [comment]
Hi @stackmystack. Yes, this is the right place for such PRs. Sorry for the delays! For this particular issue, I'm not sure how `field()` is used in general as it's not a feature we use in semgrep. That's why I'd like to refer to @maxbrunsfeld.

**Comment by aryx** [comment]
Also you get CI failures: "Error in query file "highlights.scm"

**Review by aryx — CHANGES_REQUESTED** [review]
fix the CI failure (and do not click "CI test are passing" when they are actually not passing).

**Comment by stackmystack** [comment]
Hello @aryx, I fixed the test-suite, it was working in the initial submission and got broken with a rebase which I didn't check.
All green now.

**Review by aryx — APPROVED** [review]
Why not.

**Pull request merged**
