### PR TITLE
Support import assertions

### PR DESCRIPTION
**Pull request by mskelton**
This adds support for [import assertions](https://github.com/tc39/proposal-import-assertions) which are at stage 3 and [experimental in Node](https://nodejs.org/api/esm.html#import-assertions).  Reading some other issues, I'm not sure this is desired at this stage, but I thought I would throw it out there to at least get thoughts on adding it.

Checklist:
- [ ] All tests pass in CI.
- [x] The script/parse-examples passes without issues.
- [x] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by mjambon** [comment]
Hi. Sorry for the slow reaction time. I see that the [proposal](https://github.com/tc39/proposal-import-assertions) has been demoted from stage 3 to stage 2:

> :warning: This proposal has been demoted from Stage 3 to Stage 2 in January 2023 due to https://github.com/whatwg/html/issues/7233. TC39 is working on a solution, which will require relaxing the "assert only" semantics and potentially changing the syntax. Import assertions have already been shipped in some implementations, consider the current instability when using them.

I suggest we pause until we're more confident that the syntax will stick unless you can make a strong case for it.

**Comment by mskelton** [comment]
@mjambon Yeah, I'm fine to close this with the change to stage 2.

**Comment by bennypowers** [comment]
We're back to stage 3 with a new keyword and the feature is called "import attributes" now, instead of "import assertions"

https://github.com/tc39/proposal-import-attributes

Before:

```js
import manifest from './package.json' assert { type: 'json' };
```

After

```js
import manifest from './package.json' with { type: 'json' };
```

**Comment by mskelton** [comment]
@bennypowers Yep, I opened #277 to support import attributes

**Pull request closed without merging**
