### PR TITLE
Update highlights.scm for content_tag

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Updates the surrounding tokens for content-tag, `<template>` (the entirety of the contents here are passed to a sub-language, glimmer in this case in the screenshots)

Before:
image

After: 
image

Info on content_tag:
- Rust Parser: https://github.com/embroider-build/content-tag/
- Spec: https://wycats.github.io/polaris-sketchwork/content-tag.html

Related: https://github.com/tree-sitter/tree-sitter-typescript/pull/277

Checklist:
- [x] All tests pass in CI.
- [x] The script/parse-examples passes without issues.
- [ ] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [x] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
rebased

**Comment by NullVoxPopuli** [comment]
not sure how test failures could be related? :thinking:

**Comment by NullVoxPopuli** [comment]
rebased, and green!

**Comment by amaanq** [comment]
note that this doesn't influence editor highlighting (unless your editor directly pulls *these* queries in)

**Pull request merged**
