### PR TITLE
building shared libraries for c.

### LINKED ISSUE #271: Compiling parser as shared library
In many tree-sitter projects, they have a `Makefile` to build the libraries to be used with C (I'm currently using bindings for Common Lisp).

Copying the makefile from other projects seems to work (probably it should be good if every tree-sitter repository follows the same structure).

Is the Makefile missing or some repositories uses a different build mechanism?

### PR DESCRIPTION
**Pull request by diasbruno**
Closes #271.

Checklist:
- [ ] All tests pass in CI.
- [ ] The script/parse-examples passes without issues.
- [ ] There are sufficient tests for the new fix/feature.
- [ ] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by diasbruno** [comment]
I took the files from `tree-sitter-kotlin`. Let me know if I'm missing something.

**Comment by amaanq** [comment]
Let's wait for the [bindings PR](https://github.com/tree-sitter/tree-sitter/pull/2438) to land first

**Comment by amaanq** [comment]
we've updated now (a few weeks now, sorry for not pinging you then)

**Comment by diasbruno** [comment]
@amaanq no problem. 👍

**Pull request closed without merging**
