### PR TITLE
Fix error on array destructuring that includes property access

### LINKED ISSUE #178: Incorrect parse error on array destructuring when LHS includes a property access
The following code

```
[obj.a] = [a];
```

is parsed by tree-sitter as 

```
program [0, 0] - [1, 0]
  expression_statement [0, 0] - [0, 14]
    subscript_expression [0, 0] - [0, 13]
      object: array [0, 0] - [0, 7]
        member_expression [0, 1] - [0, 6]
          object: identifier [0, 1] - [0, 4]
          property: property_identifier [0, 5] - [0, 6]
      ERROR [0, 8] - [0, 9]
      index: identifier [0, 11] - [0, 12]
```

If I remove the `.a` from the LHS, it parses without error.

### PR DESCRIPTION
**Pull request by FnControlOption**
Checklist:
- [x] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [x] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

Closes #178

### CODE REVIEW

**Comment by resolritter** [comment]
I think it would be valuable to add a test for #178 's problem specifically. The following seems to work locally:

```diff
diff --git a/test/corpus/statements.txt b/test/corpus/statements.txt
index 08466cc..296003a 100644
--- a/test/corpus/statements.txt
+++ b/test/corpus/statements.txt
@@ -6,6 +6,7 @@ a = 0;
 var b = 0;
 const c = 0;
 let d = 0;
+foo[bar.baz] = 0;
 
 ---
 (program
@@ -14,7 +15,10 @@ let d = 0;
   (variable_declaration (variable_declarator (identifier) (number)))
   (lexical_declaration
     (variable_declarator (identifier) (number)))
-  (lexical_declaration (variable_declarator (identifier) (number))))
+  (lexical_declaration (variable_declarator (identifier) (number)))
+  (expression_statement
+    (assignment_expression
+      (subscript_expression (identifier) (member_expression (identifier) (property_identifier))) (number))))
````

**Review by maxbrunsfeld — APPROVED** [review]

**Comment by mjambon** [comment]
@FnControlOption would you mind regenerating the files due to a conflict? Max approved the request already. Thanks!

**Comment by FnControlOption** [comment]
Done, sorry for the delay.

**Comment by maxbrunsfeld** [comment]
Thank you!

**Pull request merged**
