### PR TITLE
Empty bodies mustn't be an empty object

### PR DESCRIPTION
**Pull request by calixteman**
In expression for (...) { } the empty body is treated like an object because followed by an automatic_semicolon. So this expression is equivalent to to for (...) { }; and the empty object is finally an expression statement... which is of course wrong.
Anyway an object cannot be an expression_statement when it's the body, ideally we should forbid that with the grammar but it seems to be quite a pain.... so this workaround.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Can you fix this just by changing precedence? See also https://github.com/tree-sitter/tree-sitter-javascript/issues/86. I don't think we need a separate token just for empty blocks.

**Comment by calixteman** [comment]
I tried a lot of things and each one failed:
 - static pred,
 - dynamic pred with a conflict for statement_block and expression_statement
 - match the opening "{" in the scanner (but here I failed in consuming my 64 Gb of memory)
I've the impress that once the automatic_semicolon is guessed there is no way to have an other possibility...
But I'm not an expert, feel free to try and let me know what's the result.
As said, for (...) {"a":1} is valid in tree-sitter but in nodejs for example it's a failure... I don't care so much about that because I parse only valid code (I hope so :))

**Comment by calixteman** [comment]
ah nice... I didn't think about prec.right.
TIL
thanks

**Comment by maxbrunsfeld** [comment]
> each one failed

I think the problem you were seeing when using precedence is that after `{}`, an `_automatic_semicolon` token was valid because of the `(expression_statement (object))` interpretation. So the lexer returned an `_automatic_semicolon`. Then, upon seeing that token, the parser decided to reduce by `object -> '{'  '}'` because an automatic semicolon was not valid for a statement block.

**Pull request merged**
