### PR TITLE
Parse async/await

### PR DESCRIPTION
**Pull request by joshvera**
🐇

### CODE REVIEW

**Comment by joshvera** [comment]
🎁

**Comment by maxbrunsfeld** [comment]
Nice. What do you think about doing `async` method definitions and arrow functions in the same PR?

**Comment by maxbrunsfeld** [comment]
Apparently `async` can occur in object literals, not just classes: https://babeljs.io/repl/#?evaluate=false&lineWrap=false&presets=stage-0&code=obj%20%3D%20%7B%0A%20%20a%3A%20'b'%2C%0A%20%20async%20c()%20%7B%20'd'%20%7D%0A%7D

**Comment by joshvera** [comment]
@maxbrunsfeld I think we should add it to method definitions, and object literals, but not arrow functions based off of https://github.com/tc39/ecmascript-asyncawait/issues/7. What do you think?

**Comment by joshvera** [comment]
📫

**Comment by maxbrunsfeld** [comment]
🚀  the future is now

**Comment by deltab** [comment]
Why not arrow functions? They can be async too. See https://github.com/tc39/ecmascript-asyncawait/issues/7#issuecomment-196427529 and https://babeljs.io/repl/#?code=async%20()%20%3D%3E%201%0A.

**Comment by maxbrunsfeld** [comment]
@deltab This PR did add support for async arrow functions.

**Pull request merged**
