### PR TITLE
Switch from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by damieng**
The long-awaited sequel to #144

### CODE REVIEW

**Comment by damieng** [comment]
Hey @maxbrunsfeld or @patrickt are you still keen on switching from Travis to GH Actions? If so can you merge this or I can otherwise close.

**Comment by patrickt** [comment]
Definitely! Let me take a look.

**Comment by patrickt** [comment]
This looks great! Sorry for the delay!

**Comment by maxbrunsfeld** [comment]
Thanks for doing this @damieng!

**Pull request merged**
